### ISSUE TITLE
Not working when using Safari

### ISSUE THREAD

**Issue by Aristotelis1** [giacomo/ngx-cookie-consent#16]
When I test my angular app in Safari the cookies are not being saved.

version: 2.2.0

**Comment by giacomo** [comment]
@Aristotelis1 which version of safari are you using?

**Comment by Aristotelis1** [comment]
Angular: 17+
Safari: 17.5

**Comment by giacomo** [comment]
@Aristotelis1 

after looking in to the code i know basically where the problem persist - could you please try to avoid localhost in safari on a mac.

**Comment by giacomo** [comment]
closed due inactivity

**Comment by sigveholmen** [comment]
I believe this is still an issue, also on Firefox. As far as I can tell, it's related to setting the consent cookie using  SameSite=None   as opposed to SameSite=Lax, which can fail on both Safari and Firefox (and possibly other browsers that are strict in this regard). I'll post PR for this, which you can consider @giacomo

**Comment by giacomo** [comment]
@sigveholmen you are welcome
